name: Deploy

on:
  workflow_run:
    workflows: ["Release"]
    branches:
      - master
    types:
      - completed

jobs:
  fetch-latest-tag:
    name: Fetch Latest Tag
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo "Deploying to production server on branch $GITHUB_REF
