name: Deploy

on:
  workflow_run:
    workflows: ["Release"]
    branches:
      - master
    types:
      - completed

jobs:
  fetch-latest-tag:
    name: Fetch Latest Tag
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

  print-env:
    name: Print Enviroment Variables
    needs: [fetch-latest-tag]
    runs-on: ubuntu-latest
    steps:
      - name: Log Output Tag
        run: echo ${{ needs.fetch-latest-tag.outputs.VERSION }}
