name: Deploy

on:
  workflow_run:
    workflows: ["Release"]
    branches:
      - master
    types:
      - completed

jobs:
  print-env:
    name: Print Enviroment Variables
    needs: [set-env]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_REF##*/}
   