name: Release

on: ["push"]

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    steps:
      - name: Start Create Git Tag
        run: echo "TODO - Create Git Tag"

  set-env:
    runs-on: ubuntu-latest
    needs: [Start]
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Env
        id: set-env
        run: |
          echo ::set-output name=tag::"${GITHUB_REF#refs/*/}"
          
      - name: Output vars
        run: echo ${{ steps.set-env.outputs.tag }}

    outputs:
      tag: ${{ steps.set-env.outputs.tag }}