name: Release

on: ["push"]

jobs:
  fetch-last-tag:
    name: Fetch Last Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fetch Last Tag
        run : |
          git tag -l | xargs git tag -d
          git fetch --tags
          TAG=$(git describe --tags --always $(git rev-list --tags --max-count=1))
          echo "TAG=$TAG" >> $GITHUB_ENV
    outputs:
      TAG: ${{ env.TAG }}

  test-log-1:
    name: Test Log 1
    needs: [fetch-last-tag]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.TAG }}
  
  test-log-2:
    name: Test Log 2
    needs: [test-log-1]
    runs-on: ubuntu-latest
    steps:
      - run: echo "$TAG ${{ env.TAG }} ${ TAG }"

  test-log-3:
    name: Test Log 3
    needs: [test-log-2, fetch-last-tag]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.fetch-last-tag.outputs.TAG }}
      - run: echo "${{ needs.fetch-last-tag.outputs.TAG }}"
