name: Release

on:
  workflow_dispatch:
    inputs:
      test-run:
        description: 'Test (y/n)?'
        required: true
        default: 'y'

jobs:
  fetch-last-tag:
    name: Fetch Last Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fetch Last Tag
        run : |
          git tag -l | xargs git tag -d
          git fetch --tags
          TAG=$(git describe --tags --always $(git rev-list --tags --max-count=1))
          echo "TAG=$TAG" >> $GITHUB_ENV
    outputs:
      TAG: ${{ env.TAG }}

  test-log-1:
    name: Test Log 1
    needs: [fetch-last-tag]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.TAG }}
  